stages:
  download_packages:
    cmd: python src/download_packages.py params.yaml
    deps:
    - src/download_packages.py
    params:
    - download_packages
    outs:
    - packages
  preprocess:
    cmd: python src/preprocess.py params.yaml
    deps:
    - data/raw
    - src/preprocess.py
    params:
    - preprocess
    outs:
    - data/preprocessed
  baseline:
    cmd: conda run -n jazzdap_baseline python src/baseline.py params.yaml
    deps:
    - data/preprocessed
    - packages
    - src/baseline.py
    params:
    - preprocess
    outs:
    - data/baseline_output
