stages:
  preprocess:
    cmd: python src/preprocess.py params.yaml
    deps:
    - data/raw
    - src/dataset.py
    - src/preprocess.py
    params:
    - dataset
    - preprocess
    - shared
    outs:
    - exp/preprocessed
  download_packages:
    cmd: python src/download_packages.py params.yaml
    deps:
    - src/download_packages.py
    params:
    - download_packages
    outs:
    - packages
  baseline:
    cmd: conda run -n jazzdap_baseline python src/baseline.py params.yaml
    deps:
    - exp/preprocessed
    - src/baseline.py
    params:
    - preprocess
    outs:
    - exp/baseline_output
