shared:
  exp_folder: exp
  raw_data: data/raw/weimar
download_packages:
  package_dir: packages
  packages:
    baseline_1: https://github.com/dogacbasaran/ismir2018_dominant_melody_estimation.git
preprocess:
  youtube_index: csv_youtube.csv
  audio_dir: audio
  output_dir: preprocessed
  output_file: csv_youtube_filtered.csv
  wav_dir: preprocessed/wdb_wavs
dataset:
  sfnmf_dir: preprocessed/sfnmf
  audio_dir: wjd_solos
  patch_dir: wjd_solos_patch
  weimardb: data/raw/weimar/wjazzd.db
  resample_rate: 22050
baseline:
  repo: packages/baseline_1
  input_data: preprocessed/wdb_wavs
  Fs: 22050
  hop: 256.0
  pitch_corrected: False
  output_folder: baseline_output
  h5py_folder: h5py_files
  weights_path: predict/weights_C-RNN.h5
  melody_folder: csv_melody
baseline_evaluation:
  output_folder: baseline_evaluation
  predictions_folder: baseline_output/csv_melody
  pianoroll_folder: pianoroll
  b1_output_file: sf_nmf_evaluation.csv
  melodia_suffix: _vamp_mtg-melodia_melodia_melody.csv
  melodia_folder: baseline_output/melodia
  b2_output_file: melodia_evaluation.csv
sfnmf:
  Fs: 22050
  hop: 256.0
  save: True
  output_folder: preprocessed/sfnmf
crnn:
  batch_size: 16
  number_of_patches: 20
  patch_size: 25
  segment_length: 500
  feature_size: 301
  number_of_classes: 63
  step_notes: 5
  RNN: GRU
  number_of_channels: 1
crnn_trainer:
  device: 3
  epochs_num: 200
  validation_period: 10
  batch_size: 64
  lr: 0.0001
  weight_decay: 0.0001
  