weimar_dataset:
  data_variant: noaudio #raw_data    #could be changed to raw_data_demucs
  weimardb: data/raw/weimar/wjazzd.db
  raw_data: data/raw/weimar/wjd_solos
  raw_data_demucs: exp/preprocessed/separated
  feature_type: sfnmf    #crepe
  feature_variant: default #demucs_frontend
  labeling_type: onsetsandframes #
sampler:
  cache_folder: exp/data_cache
sfnmf_features:
  Fs: 22050
  hop: 256.0
  sfnmf_path: exp/preprocessed/sfnmf
  demucs_sfnmf_path: exp/preprocessed/sfnmf_separated
crepe_features:
  Fs: 44100
  hop: 441.0
  window: 0.01
  crepe_path: exp/preprocessed/crepe_activations
crnn_model:
  number_of_patches: 20
  patch_size: 25
  segment_length: 500
  feature_size: 301
  number_of_classes: 62
  step_notes: 5
  RNN: GRU
  number_of_channels: 1
onsetsandframes_model:
  segment_length: 500
  feature_size: 301
  number_of_classes: 61
  num_label_channels: 3
crnn_trainer:
  device: 7
  epochs_num: 200
  validation_period: 10
  batch_size: 64
  lr: 0.001
  lr_final: 0.00001
  weight_decay: 0.0001
  label_smoothing: 0.1
  model_folder: exp/models
  data_tag: 91 #91-separated